version: '3.9'

services:
  calmpal_db:
    container_name: calmpal_db
    image: postgres:15.2
    environment:
      - POSTGRES_DB=$DB_NAME
      - POSTGRES_USER=$DB_USERNAME
      - POSTGRES_PASSWORD=$DB_PASSWORD
    ports:
      - 5434:5432
    networks:
      - calmpal_network
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: on-failure
  backend_db_migrations:
    container_name: backend_db_migrations
    build:
      context: .
      dockerfile: backend/Dockerfile.db-migrations
    command: |
      printenv
      bash -c npm run prestart -w backend
    networks:
      - calmpal_network

networks:
  calmpal_network:
    driver: bridge

volumes:
  pgdata:
    driver: local


